disable_existing_loggers: true
formatters:
    precise:
        datefmt: '%Y-%m-%d %H:%M:%S'
        format: '%(asctime)s [%(levelname)s] <PID %(process)d:%(processName)s> : %(threadName)s
            - %(module)s - %(filename)s - %(funcName)s - %(lineno)s %(message)s'
    standard:
        datefmt: '%Y-%m-%d %H:%M:%S'
        format: '%(asctime)s [%(levelname)s] : %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        formatter: standard
        level: INFO
        stream: ext://sys.stdout
    critical_file_handler:
        backupCount: 20
        class: logging.handlers.RotatingFileHandler
        encoding: utf8
        filename: logs/critical.log
        formatter: standard
        level: CRITICAL
        maxBytes: 10485760
    debug_file_handler:
        backupCount: 20
        class: logging.handlers.RotatingFileHandler
        encoding: utf8
        filename: logs/debug.log
        formatter: standard
        level: DEBUG
        maxBytes: 10485760
    error_file_handler:
        backupCount: 20
        class: logging.handlers.RotatingFileHandler
        encoding: utf8
        filename: logs/errors.log
        formatter: precise
        level: ERROR
        maxBytes: 10485760
    info_file_handler:
        backupCount: 20
        class: logging.handlers.RotatingFileHandler
        encoding: utf8
        filename: logs/info.log
        formatter: standard
        level: INFO
        maxBytes: 10485760
    warn_file_handler:
        backupCount: 20
        class: logging.handlers.RotatingFileHandler
        encoding: utf8
        filename: logs/warn.log
        formatter: standard
        level: WARN
        maxBytes: 10485760
loggers:
    <module.x>:
        handlers:
        - info_file_handler
        - error_file_handler
        - critical_file_handler
        - debug_file_handler
        - warn_file_handler
        level: DEBUG
        propogate: true
    <module>:
        handlers:
        - console
        - info_file_handler
        - error_file_handler
        - critical_file_handler
        - debug_file_handler
        - warn_file_handler
        level: DEBUG
        propogate: false
notificationId: 226
root:
    handlers:
    - console
    - info_file_handler
    - warn_file_handler
    - error_file_handler
    - critical_file_handler
    level: DEBUG
    propogate: true
version: 1
