* 机器学习概述2

** 机器学习概念
 - *拟合*: 构建的算法符合给定数据的特征
 - *$x^{i}$*: 表示第$i$个样本的$x$向量
 - *$x_{i}$*: $x$向量的第$i$维度的值
 - *鲁棒性*: 也就是健壮性,稳健性,强健性,是系统的健壮性;当存在异常数据的时候,算法也会拟合数据
 - *过拟合*: 算法太符合样本数据的特征,对于实际产生中的数据特征无法拟合
 - *欠拟合*: 算法不太符合样本的数据特征

** 机器学习常用框架
*** scikit-learn(Python)
*网址*
https://scikit-learn.org/stable/

简称: sk-learn
机器学习邻域里最常用的框架

*** Mahout(Hadoop)
Hadoop生态圈基于Mapreduce

*** Spark MLib(Spark)

** sk-learn
常用英文单词:
 1. Classification 分类
 2. Regression: 回归
 3. Clustering:聚类
 4. Dimensionality reduction: 降维
 5. Model Selection: 模型选择
 6. Preprocessing: 预处理

sk-learn的API地址:
https://scikit-learn.org/stable/modules/classes.html

*** 安装sk-learn

#+BEGIN_SRC shell
pip3 install scikit-learn
#+END_SRC


** 机器学习之商业场景
*个性化推荐*
个性化指的是根据各种因素来改变用户体验和呈现给用户内容,这些因素可能包含用户的行为数据和外部因素;推荐常批量系统向用户呈现一个用户可能感兴趣的物品列表.

*精准营销*
从用户群众中找出特定的要求的营销对象

*客户细分*
试图将用户群体分为不同的组,根据给定的用户特征进行客户分组.

*预测建模及分析*
根据已有的数据进行建模,并使用得到的模型预测未来

** 机器学习,数据分析,数据挖掘区别与联系
*** 数据分析
数据分析是指用适当的统计分析方法对收集的大量数据进行分析,并提取有用的信息,以及形成结论,从而对数据进行详细的研究和概括过程.
在实际工作中,数据分析可帮助人们做出判断;数据分析一般而言可以分为统计分析,探索性数据分析和验证性数据分析三大类.

*** 数据挖掘
一般批量从大量的数据中通过算法搜索隐藏于其中的信息的过程.
通常通过统计,检索,机器学习,模式匹配等诸多方法来实现这个过程.

*** 机器学习
是数据分析和数据挖掘的一种比较常用,比较好的手段

** 机器学习分类
机器学习本质上也是个工具,应用在不同邻域的时候都是这样一个工具,去应用.
机器学习中比较关键的这样一个东西.
分类和聚类到底是不是一回事

*** 有监督学习
用已知某种或某些特性的样本作为训练集,以建立一个数学模型,再用已建立的模型来预测未知样本,此种方法被称为有监督学习,是最常用的一种机器学习方法.是从标签化训练数据集中推断出模型的机器学习任务




*有监督学习的定义是最关键的是什么呢?*
  从标签化的训练数据集中推断出模型机器学习任务
前面都是废话,没有用,最关键的要看的就是:从标签化的训练数据集中推断出模型机器学习任务

*什么是标签*
你有有标签的数据吗?
标签指的是谁?就是Y,Y可以称之为Label,也可以称之为Target(我们的目标值)
一个任务首先要定义一个目标,这个目标对应的是谁?我们的目标要对这个任务进行合理的建模和预测,也就是说我们的目标在进行预测的时候有一个对应的y的值的话,
x1第一个特征,xn第n个特征,矩阵一般是有m行n列的这样一个矩阵,所以我们一般去写的时候这个数据集中一般会有m条观测值以及n列的这样一个特征,然后最终会有一个目标值的y,如果有y,我们就称之为有监督学习,我们就要使用有监督学习进行模型的构建,实际上我们在日常的业务当中能够多使用有监督学习就多使用有监督学习,比如说在有x1, x2, x3, \ldots, xn以及y的情况下就老老实实用有监督学习了,就别用无监督学习.

如果数据集中包含有y的话,
标签是什么?
比如说有一张猫的图片,我们都知道它是只猫,但是计算机不知道它是只猫,怎么办呢?给这张图片打上个标签,然后计算机就知道它是只猫了,后面计算机根据这个标签对所有的猫进行学习就能通过这一只猫认识所有的猫了.
Y指的是谁?Label和Target

只知道x1到xn而不知道y,通过无监督学习去归纳出来一般规律,为什么不建议使用无监督学习呢?会


*** 无监督学习
与监督学习相比,

知道了有监督学习的定义了,无监督学习的定义是什么?我在算法构建的过程中不考虑Y的值,只通过特征信息去归纳出一些新的规律出来,这个方法就称之为无监督学习.两个的区别就是一个有y,一个没有y,这是最简单的记忆方式.所以总结起来正式的说法是:无监督学习的训练集中没有人为的标注的结果,在非监督的学习过程中,数据并不被特别标识,学习模型是为了推断出数据的一些内存结构.

*推断出数据的一些内在结构*这是无监督学习学习的作用

为什么不建议使用无监督学习呢
在聚类的时候会好好跟大家说
现在需要大家明白一个点就是:无监督学习有时候需要我们进行辅助的规律总结,
无监督学习需要我们推断一些结构,但是在推断一些结构的时候可能会因为人为的主观臆断而出现一些偏差,这个就不是纯数学能够证明我是对的了,这个时候就是人在瞎猜.

老师在没有y值的情况怎么办?是不是只能进行无监督学习了呢? 
没有Y值的时候,自己给数据打标签,自己把Y做出来.然后进行有监督学习 
很多情况下,在实际的工作业务中很多的工作量都是给数据打标签,你可能花半个半个月的时间,五六个人就坐那儿天天打标签,几万条数据坐那儿打标签打个三四天很正常.


所以就需要注意了,如果说真的是说在没有标签的情况下,你看看有没有合理的方式先把标签获取过来. 如果没有合理的渠道,就看看能不能进行人为地打标签再进行有监督学习的学习,这样做的结果会更好些.

*** 半监督学习
看上面有监督学习和无监督学习的定义,就是一半有一半无呗
意思就是用少量的有标注的样本和大量未标注的样本进行训练和分类,这样是有监督学习和无监督学习的结合.

考虑如何利用少量的瓢样本和大量的未瓢样本进行训练和分类的问题,
是有监督学习和无监督学习的结合.

这就是机器学习大致的一个分类

